### ISSUE TITLE
Replace Tesla API Code w/Library

### ISSUE THREAD

**Issue by morrisonbrett** [morrisonbrett/TeslaCommand#18]
Looks like @jsgoecke wrote a very cool library in Go: https://github.com/jsgoecke/tesla

Port to this!

**Comment by jsgoecke** [comment]
Please don't hesitate to open issues or send pull requests if you need anything. There is test coverage in there, so should be able to ensure things are copacetic.

**Comment by morrisonbrett** [comment]
Thanks @jsgoecke. I just ported to your library! https://github.com/morrisonbrett/TeslaCommand/commit/7ca736a32ca63891409a38ffc58b18f9e020e8db

**Comment by morrisonbrett** [comment]
Done.  Merged PR https://github.com/morrisonbrett/TeslaCommand/pull/19
